addons:
  postgresql: 9.3
  sonarcloud:
    organization: guilhermepaciulli
    token:
      secure: pqPXGLO0wySG1pzLpVfL6dcFW9o50MyyJYnW54GLmEbX+kKZQe/1xgUlZ5PG7OTEtt3Y4Gneq/AuEDRQwaoqrlNVWnBjbidUnItc5VSDPFs/jknHhi4/rjWDFVaLYCUG7zr2R4f7sAytboYXJaoa6CXhGG3JMNAJyJVo2QOY+9cjvqji9pL6NTLG/8ZfejCz2MbYWPOy3YCGwgKWNM8l40y1pKLVD37htuTe/oSJZLYXpeaI96JZmKnCyZpHpw5VO/ISnGAK8evKT42f5zQ/eWKuCKOZ+V/E3lfLGcM0wJu4aGHepsurY8VNADLZHAubxWcWoJu0aYxlYfPXakChyxcjQ/YPQC9yJ7DtV8YbB1KP+aEFM/WgaiZSywClAZiNpjxjZdZsgsv2qm6h3/7K25Cfmwz0orGjYrEiFmUBg9UiPoWxrYXXLzvOIXtiXvzGx1GBFuSkgmhj7uBA6OmZ2c6Wvun2Gg6qmHD99Yx6I5o2v7Jo3FRjCCArAeaSIeB/e3lVOUkLTudIDK/qi+VVHJSYXFvasJ1OGGXLFVR25mtT8SD7IAryaU+0LEpTkXhoFkB8MiY3q+h0ICV/RZstB+2RRmBY7+yIB7PizclG8Aq8heFPpFASkP5bENsYS43OG69E0g1upFLzkoTe40s4qEb5IAsxuV+PqSh3YWNbAYc=

before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
- 2.6.5
script:
- bundle exec rails db:migrate RAILS_ENV=test
- COVERAGE=true bundle exec rspec  --require rails_helper
- sonar-scanner
env:
  RAILS_ENV: test
  global:
  - secure: YCtSJV/twDnm7obCAkHX2twvoEIs1RKUbsP5NGSfvLhjQJGbJB+A3BXQA38Swh/HAKJ3PrHAeVqJv6tAv8rSIhTtC6To/I5e9XG7aL+LP1bMrkVOIpOj4kCQgJnIY6fXFA3MmSlTIv9To2RoY/Wfk3NWX7pUfMKCqFTjM5OwndJwerXJ0nNB8S0V7gystEzQhJBAPcICIRwPvxEhtpCetW4vZ1BNxz6/y5gKGrYxYeVoAPcwD+RBeaVLKjXAPyNg9nxxfNlkCgb4fOsG9mV1CD00m3R8/6lPl3CeoAjF9FvTriq7fFN51CZ9lnQFpLlePb/a4AM/AcYef4AMZ9d0Iy8UQBKy79QEpMPf+3KJOhFbXCOE13SHPVHvS0wc3L4iJCMyPEMylKaXqnAZiE8Vh7nuskmN8uFCv+bXgwDM+GxJ10oFrUpenyhvtmC9KGzISMf145aK/sq8fWigzdC8tK4qu0Vsvdr5zM5qKmxfelKqgYLbTvmN6VeVnjnHBfOeHPniN8ENRyKxe4WtJ5ekAqqI3GQ2dls2lcU5VPbvXI9HJeDCAT59rq1bPWUK51QKlManqPOT1Ooqdgeq3gfA60fVCmmaYYK4WsheWIBHMVMecMhlMfiKO0r5BT81I9+T4xXT29df2TdrAMumCpMSb7FkvcsrDGH8hh9x/R6Vo78=
